# Generated by Django 5.2 on 2025-06-09 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheweb', '0003_cart_added_at_cart_cart_description_cart_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_descriptions', to='clotheweb.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='cart_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_prices', to='clotheweb.product'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='clotheweb.product'),
        ),
    ]
