# Generated by Django 5.2 on 2025-06-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheweb', '0004_alter_cart_cart_description_alter_cart_cart_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
            ],
        ),
    ]
