# Generated by Django 5.2 on 2025-06-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clotheweb', '0005_cartdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='cart_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='custom_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
