# Generated by Django 5.1.6 on 2025-03-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WifiScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bssid', models.CharField(max_length=50)),
                ('essid', models.CharField(blank=True, max_length=100, null=True)),
                ('power', models.IntegerField()),
                ('beacons', models.IntegerField()),
                ('data', models.IntegerField()),
                ('channel', models.IntegerField()),
                ('encryption', models.CharField(max_length=50)),
                ('cipher', models.CharField(max_length=50)),
                ('auth', models.CharField(max_length=50)),
            ],
        ),
    ]
