# Generated by Django 5.1.6 on 2025-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifiscan',
            name='data',
        ),
        migrations.RemoveField(
            model_name='wifiscan',
            name='encryption',
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='first',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='idlen',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='ip',
            field=models.CharField(blank=True, default='0.0.0.0', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='iv',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='key',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='last',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='privacy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wifiscan',
            name='speed',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='auth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='beacons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='bssid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='channel',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='cipher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wifiscan',
            name='power',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
