# Generated by Django 5.1.6 on 2025-04-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_remove_wifiscan_data_remove_wifiscan_encryption_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='location',
            name='date',
        ),
        migrations.RemoveField(
            model_name='location',
            name='loc',
        ),
        migrations.RemoveField(
            model_name='location',
            name='time',
        ),
        migrations.RemoveField(
            model_name='location',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
