# Generated by Django 5.1.6 on 2025-04-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_remove_location_camera_remove_location_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location_name',
        ),
    ]
