# Generated by Django 5.1.6 on 2025-04-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0005_rename_name_location_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
        migrations.AddField(
            model_name='location',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
