# Generated by Django 5.2 on 2025-05-02 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0006_location_audio_location_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationWithLatLong',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='gps.location')),
                ('pkey', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(blank=True, max_length=50, null=True)),
                ('ssid', models.CharField(blank=True, max_length=100, null=True)),
                ('signal', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('longi', models.FloatField(blank=True, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            bases=('gps.location',),
        ),
    ]
