# Generated by Django 5.1.6 on 2025-03-23 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-id', '-created']},
        ),
    ]
