# Generated by Django 5.2 on 2025-05-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_message_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-id', '-created']},
        ),
    ]
